apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-go-mock-api
  namespace: test-a
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-mock-api
  minReplicas: 8
  maxReplicas: 16
  targetCPUUtilizationPercentage: 70
